name: OpeanAPI diff

on:
  pull_request_target:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: debug
        run: |
          echo "PR_NUMBER=${{ github.event.number }}"
          echo "PR_HEAD_REF=${{ github.event.pull_request.head.ref }}"
          echo "PR_HEAD_REPO=${{ github.event.pull_request.head.repo.full_name }}"
          echo ${{ github }}
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: base
      - name: Run OpenAPI Diff (from HEAD revision)
        id: run-diff
        uses: janinko/openapi-diff-action@v0.0.2
        with:
          head-spec: head/rest-api/pnc-openapi.yaml
          base-spec: base/rest-api/pnc-openapi.yaml
      - name: Check changes
        id: check-change
        run: |
          if grep "No differences. Specifications are equivalents" openapi-diff.out; then
            echo "changed=no" >> $GITHUB_OUTPUT
          else
            echo "changed=yes" >> $GITHUB_OUTPUT
          fi
      - name: Comment on PR
        if: steps.check-change.outputs.changed == 'yes'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            # REST API CHANGED
            ```
            ${{ steps.run-diff.outputs.diff-output }}
            ```
      - name: Check compatibility break
        if: steps.check-change.outputs.changed == 'yes'
        run: |
          if grep "API changes broke backward compatibility" openapi-diff.out; then
            exit 1
          fi
